import { FrameTemplate } from '../types/frame';

export const FRAME_TEMPLATES: FrameTemplate[] = [
  {
    id: 'navy_baroque_gallery',
    name: 'Royal Navy Gallery Wall',
    category: 'gallery_wall',
    description: 'Spotlight on deep navy wall with ornate gilded gold frame and bilingual memorial quote.',
    badge: 'Original Theme',
    canvasWidth: 2000,
    canvasHeight: 1414,
    // Frame aperture positioned on the left side of the gallery wall
    aperture: {
      x: 0.228,
      y: 0.288,
      width: 0.245,
      height: 0.388,
      aspectRatio: 0.63,
    },
    wallStyle: 'navy_spotlight',
    frameStyle: 'baroque_gold',
    hasSpotlight: true,
    spotlightX: 0.35,
    spotlightY: 0.05,
    hasDrapery: true,
    hasWoodFloor: true,
    defaultText: {
      line1: 'ONE STORY',
      line2: 'A MILLION',
      highlight: 'Memories',
      localized: '1 เรื่องราว 1 ล้านความทรงจำ',
      showText: true,
      textColor: '#ffffff',
      highlightColor: '#facc15',
      fontStyle: 'cinzel',
    },
    defaultMatting: {
      enabled: false,
      color: '#ffffff',
      widthPercent: 6,
    },
  },
  {
    id: 'solo_gilded_masterpiece',
    name: 'Gilded Baroque Solo',
    category: 'standalone',
    description: 'Majestic antique gold carved frame occupying center focus with rich depth.',
    badge: 'Masterpiece',
    canvasWidth: 1600,
    canvasHeight: 2000,
    aperture: {
      x: 0.21,
      y: 0.17,
      width: 0.58,
      height: 0.66,
      aspectRatio: 0.88,
    },
    wallStyle: 'dark_luxury',
    frameStyle: 'ornate_gold_thick',
    hasSpotlight: true,
    spotlightX: 0.5,
    spotlightY: 0.1,
    hasDrapery: false,
    hasWoodFloor: false,
    defaultText: {
      line1: 'MASTERPIECE',
      line2: 'TIMELESS',
      highlight: 'Moments',
      localized: 'บันทึกความทรงจำอันทรงคุณค่า',
      showText: false,
      textColor: '#f8fafc',
      highlightColor: '#f59e0b',
      fontStyle: 'playfair',
    },
    defaultMatting: {
      enabled: true,
      color: '#f8fafc',
      widthPercent: 7,
    },
  },
  {
    id: 'museum_salon',
    name: 'Grand Museum Exhibition',
    category: 'gallery_wall',
    description: 'Museum gallery with rich brass picture lamp overhead, mahogany frame, and exhibition nameplate.',
    badge: 'Art Museum',
    canvasWidth: 2000,
    canvasHeight: 1500,
    aperture: {
      x: 0.28,
      y: 0.22,
      width: 0.44,
      height: 0.52,
      aspectRatio: 0.85,
    },
    wallStyle: 'museum_taupe',
    frameStyle: 'vintage_walnut',
    hasSpotlight: true,
    spotlightX: 0.5,
    spotlightY: 0.08,
    hasDrapery: false,
    hasWoodFloor: true,
    defaultText: {
      line1: 'SALON DES ARTS',
      line2: 'PERMANENT',
      highlight: 'Exhibition',
      localized: 'นิทรรศการแห่งความทรงจำ',
      showText: true,
      textColor: '#e2e8f0',
      highlightColor: '#eab308',
      fontStyle: 'cinzel',
    },
    defaultMatting: {
      enabled: true,
      color: '#fefce8',
      widthPercent: 8,
    },
  },
  {
    id: 'slate_minimal',
    name: 'Modern Slate Studio',
    category: 'modern',
    description: 'Contemporary minimalist charcoal gallery wall with slim anodized black frame & wide white matting.',
    badge: 'Modernist',
    canvasWidth: 1920,
    canvasHeight: 1280,
    aperture: {
      x: 0.32,
      y: 0.18,
      width: 0.36,
      height: 0.62,
      aspectRatio: 0.58,
    },
    wallStyle: 'slate_minimal',
    frameStyle: 'modern_black',
    hasSpotlight: true,
    spotlightX: 0.5,
    spotlightY: 0.05,
    hasDrapery: false,
    hasWoodFloor: true,
    defaultText: {
      line1: 'ARCHIVE',
      line2: 'VOL. 01',
      highlight: 'Essence',
      localized: 'เรื่องราวในความทรงจำ',
      showText: true,
      textColor: '#f1f5f9',
      highlightColor: '#38bdf8',
      fontStyle: 'modern',
    },
    defaultMatting: {
      enabled: true,
      color: '#ffffff',
      widthPercent: 9,
    },
  },
  {
    id: 'scandinavian_oak',
    name: 'Nordic Sunlit Wood',
    category: 'modern',
    description: 'Warm natural oak wood frame on light cream wall with gentle morning sunbeam.',
    badge: 'Warm & Airy',
    canvasWidth: 1800,
    canvasHeight: 1350,
    aperture: {
      x: 0.30,
      y: 0.18,
      width: 0.40,
      height: 0.60,
      aspectRatio: 0.67,
    },
    wallStyle: 'warm_wood',
    frameStyle: 'natural_oak',
    hasSpotlight: true,
    spotlightX: 0.3,
    spotlightY: 0.1,
    hasDrapery: false,
    hasWoodFloor: true,
    defaultText: {
      line1: 'SWEET DAYS',
      line2: 'FOREVER',
      highlight: 'Cherished',
      localized: 'ทุกช่วงเวลาที่แสนพิเศษ',
      showText: true,
      textColor: '#334155',
      highlightColor: '#d97706',
      fontStyle: 'playfair',
    },
    defaultMatting: {
      enabled: true,
      color: '#fdfbf7',
      widthPercent: 8,
    },
  },
  {
    id: 'vintage_polaroid_desk',
    name: 'Instant Film Memory',
    category: 'polaroid',
    description: 'Nostalgic instant photograph on vintage desk with customizable handwritten caption.',
    badge: 'Polaroid',
    canvasWidth: 1600,
    canvasHeight: 1600,
    aperture: {
      x: 0.22,
      y: 0.16,
      width: 0.56,
      height: 0.56,
      aspectRatio: 1.0,
    },
    wallStyle: 'polaroid_desk',
    frameStyle: 'polaroid_border',
    hasSpotlight: false,
    spotlightX: 0.5,
    spotlightY: 0.2,
    hasDrapery: false,
    hasWoodFloor: false,
    defaultText: {
      line1: 'SUMMER MEMORY',
      line2: 'BEST DAYS',
      highlight: 'Together',
      localized: 'วันเวลาที่เรายิ้มด้วยกัน',
      showText: true,
      textColor: '#1e293b',
      highlightColor: '#e11d48',
      fontStyle: 'classic',
    },
    defaultMatting: {
      enabled: false,
      color: '#ffffff',
      widthPercent: 0,
    },
  },
];
